application: bani
version: 1
runtime: python
api_version: 1

handlers:

- url: /hora.json
  script: horaagora.py

- url: /
  upload: static/index.html
  static_files: static/index.html

