application: bani
version: 2
runtime: python
api_version: 1

handlers:

- url: /hora.json
  script: horaagora.py
  
- url: /mapa.json.*
  script: mapa.py

- url: /
  upload: html/index.html
  static_files: html/index.html
  
- url: /timer
  upload: html/timer.html
  static_files: html/timer.html
  
- url: /mundo
  upload: mapa/index.html
  static_files: mapa/index.html

- url: /anonovo
  upload: html/anonovo.html
  static_files: html/anonovo.html

- url: /mapa
  static_dir: mapa
  
- url: /placar
  upload: html/placar.html
  static_files: html/placar.html

- url: /sitemap\.xml
  upload: html/sitemap.xml
  static_files: html/sitemap.xml

- url: /robots\.txt
  upload: html/robots.txt
  static_files: html/robots.txt

- url: /favicon\.ico
  static_files: style/favicon.ico
  upload: style/favicon.ico

- url: /style
  static_dir: style
  
- url: /js
  static_dir: js
  
- url: /timer.manifest
  upload: html/timer.manifest
  static_files: html/timer.manifest