application: bani
version: 1
runtime: python
api_version: 1

handlers:

- url: /hora.json
  script: horaagora.py
  
- url: /mapa.json
  script: mapa.py

- url: /
  upload: static/index.html
  static_files: static/index.html
  
- url: /mundo
  upload: mapa/index.html
  static_files: mapa/index.html

- url: /mapa
  static_dir: mapa
